# Generated by Django 5.1.2 on 2025-10-12 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("concepts", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("courses", "0001_initial"),
        ("ncore", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptBasedProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=255, verbose_name="Title"),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "problem_type",
                    models.CharField(
                        choices=[("ML", "Machine Learning"), ("DL", "Deep Learning")],
                        default="ML",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("editorial_description", models.TextField(blank=True, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                ("last_updated_timestamp", models.DateTimeField(auto_now=True)),
                ("creation_timestamp", models.DateTimeField(auto_now_add=True)),
                ("accepted_submissions", models.IntegerField(default=0)),
                ("total_submissions", models.IntegerField(default=0)),
                ("code_editor_template", models.TextField(blank=True, null=True)),
                ("ideal_solution_code", models.TextField(blank=True, null=True)),
                ("validation_testcases", models.JSONField(blank=True, null=True)),
                ("submission_testcases", models.JSONField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.course",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="ncore.tag")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DailyContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("date", models.DateField(unique=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="concepts.concept",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DatasetBasedProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=255, verbose_name="Title"),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "problem_type",
                    models.CharField(
                        choices=[("ML", "Machine Learning"), ("DL", "Deep Learning")],
                        default="ML",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("editorial_description", models.TextField(blank=True, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                ("last_updated_timestamp", models.DateTimeField(auto_now=True)),
                ("creation_timestamp", models.DateTimeField(auto_now_add=True)),
                ("accepted_submissions", models.IntegerField(default=0)),
                ("total_submissions", models.IntegerField(default=0)),
                ("evaluation_metrics_dict", models.JSONField()),
                (
                    "test_data_file_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("data_available_to_user_file_path", models.CharField(max_length=500)),
                (
                    "ideal_metrics_json_file_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "author",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.course",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="ncore.tag")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("note", models.TextField(default="")),
                ("note_creation_timestamp", models.DateTimeField(auto_now_add=True)),
                ("note_update_timestamp", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("code", models.TextField(blank=True, null=True)),
                (
                    "verdict",
                    models.IntegerField(
                        choices=[
                            (1, "In Queue"),
                            (2, "Processing"),
                            (3, "Accepted"),
                            (4, "Wrong Answer"),
                            (5, "Time Limit Exceeded"),
                            (6, "Compilation Error"),
                            (7, "Runtime Error"),
                            (8, "Judgement Failed"),
                        ],
                        default=1,
                    ),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
                ("time_taken", models.FloatField(blank=True, null=True)),
                ("memory_taken", models.FloatField(blank=True, null=True)),
                ("failed_testcase_info", models.JSONField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserDailyProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solved", models.BooleanField(default=False)),
                ("concept_read", models.BooleanField(default=False)),
                (
                    "daily_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems.dailycontent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "dislike_by_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="disliked_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "like_by_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["parent_comment"], name="problems_co_parent__0ea152_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="dailycontent",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="problems_da_content_a8f602_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="problems_no_content_120a00_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="problems_su_content_232ef5_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userdailyprogress",
            unique_together={("user", "daily_content")},
        ),
    ]
