# Generated by Django 5.1.2 on 2025-10-12 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "organisation_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "language_selected",
                    models.CharField(
                        choices=[("eng", "English"), ("hin", "Hindi")],
                        default="eng",
                        max_length=255,
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Profile photo (max 2MB)",
                        null=True,
                        upload_to="profile_photos/",
                    ),
                ),
                ("is_premium_user", models.BooleanField(default=False)),
                ("bio", models.TextField(blank=True, null=True)),
                ("occupation", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "kaggle_profile_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("github", models.URLField(blank=True, max_length=500, null=True)),
                ("twitter", models.URLField(blank=True, max_length=500, null=True)),
                ("portfolio", models.URLField(blank=True, max_length=500, null=True)),
                ("linkedin", models.URLField(blank=True, max_length=500, null=True)),
                ("pronouns", models.CharField(blank=True, max_length=50, null=True)),
                ("interests", models.TextField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("current_day_concept_read", models.BooleanField(default=False)),
                ("current_day_problem_solved", models.BooleanField(default=False)),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("is_onboarding_complete", models.BooleanField(default=False)),
                ("is_email_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
